# Generated by Django 5.2.17 on 2026-08-27 16:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("TICKET_CREATED", "Ticket Created"),
                            ("TICKET_ASSIGNED", "Ticket Assigned"),
                            ("TICKET_REASSIGNED", "Ticket Reassigned"),
                            ("TICKET_STATUS_CHANGED", "Ticket Status Changed"),
                            ("TICKET_PRIORITY_CHANGED", "Ticket Priority Changed"),
                            ("COMMENT_ADDED", "Comment Added"),
                            ("CATEGORY_CREATED", "Category Created"),
                            ("CATEGORY_UPDATED", "Category Updated"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("entity_type", models.CharField(db_index=True, max_length=50)),
                ("entity_id", models.UUIDField(db_index=True)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id", "created_at"],
                        name="audit_entity_created_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"], name="audit_actor_created_idx"
                    ),
                    models.Index(
                        fields=["action", "created_at"], name="audit_action_created_idx"
                    ),
                ],
            },
        ),
    ]
